## GET REQUEST
GET localhost:4000/patients

###

## POST REQUEST
POST http://localhost:4000/patients
Content-Type: application/json


{
  "name": "hamza",
  "dateOfBirth" : "2003-01-01",
  "dateRegistered" : "2003-01-01",
  "email" : "hamza@gmail.com"
}